spring:
  application:
    name: Blogging
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/blog_db
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  images:
    path: images/

