spring:
  application:
    name: Blogging
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/blog_db
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: update